const $=(id)=>document.getElementById(id);let currentRules;let status;
const formatError=(error)=>error?.message||String(error);function notice(message,error=false){const el=$('notice');el.textContent=message;el.className=`show${error?' error':''}`;clearTimeout(notice.timer);notice.timer=setTimeout(()=>el.className='',4200)}
async function inspect(){try{status=await window.cdpCollector.inspect();$('clientState').textContent=status.state==='running'?'已检测':'需要处理';$('clientMessage').textContent=status.message;$('version').textContent=status.appVersion||'未读取';$('cdpState').textContent=status.cdpReady?'已启用':'未启用';$('restart').checked=!status.cdpReady}catch(error){notice(formatError(error),true)}}
async function loadSettings(){const s=await window.cdpCollector.loadSettings();$('endpoint').value=s.uploadEndpoint;$('platform').value=s.platform;$('priority').value=s.priority;$('autoUpload').checked=s.autoUpload;$('token').placeholder=s.tokenConfigured?'已安全保存，留空保持不变':'输入专用上传令牌'}
function showRules(rules,summary){currentRules=rules;$('preview').textContent=JSON.stringify(rules,null,2);$('resultSummary').textContent=summary||`${rules.exactOfficialVersion} · ${rules.id}`;$('exportRules').disabled=false;$('uploadRules').disabled=false}
$('inspect').onclick=inspect;$('saveSettings').onclick=async()=>{try{await window.cdpCollector.saveSettings({uploadEndpoint:$('endpoint').value,platform:$('platform').value,priority:Number($('priority').value),autoUpload:$('autoUpload').checked,uploadToken:$('token').value});$('token').value='';await loadSettings();notice('上传设置已安全保存')}catch(error){notice(formatError(error),true)}};
$('collect').onclick=async()=>{const button=$('collect');button.disabled=true;button.textContent='正在采集…';try{const result=await window.cdpCollector.collect({consent:$('consent').checked,restartClient:$('restart').checked});showRules(result.rules,result.uploadMessage||'采集完成，尚未上传');notice(result.uploadMessage||'规则采集完成',Boolean(result.uploadMessage?.includes('失败')));await inspect()}catch(error){notice(formatError(error),true)}finally{button.disabled=false;button.textContent='授权并开始采集'}};
$('exportRules').onclick=async()=>{try{const file=await window.cdpCollector.exportRules(currentRules);if(file)notice(`已导出：${file}`)}catch(error){notice(formatError(error),true)}};
$('importRules').onclick=async()=>{try{const rules=await window.cdpCollector.importRules();if(rules){showRules(rules,'已导入，等待审核或上传');notice('规则文件已导入并通过校验')}}catch(error){notice(formatError(error),true)}};
$('uploadRules').onclick=async()=>{try{const result=await window.cdpCollector.uploadRules(currentRules);notice(`规则 ${result.id} 已上传`)}catch(error){notice(formatError(error),true)}};
Promise.all([inspect(),loadSettings()]).catch((error)=>notice(formatError(error),true));
